export interface ActivityArgument {
  id?: string;
  name: string;
  description?: string;
  descriptionVi?: string;
  type: string;
  keywordArgument?: string; // Tên tham số trong python function (e.g. "selector")
  isRequired?: boolean;
  defaultValue?: any;
  activityTemplateId?: string;
}

export interface ActivityReturnValue {
  id?: string;
  type: string;
  description?: string;
  descriptionVi?: string;
  displayName?: string;
  displayNameVi?: string;
  activityTemplateId?: string;
}

export interface ActivityTemplate {
  id: string;
  name: string; // Display name của template (e.g. "Click")
  nameVi?: string;
  description?: string;
  descriptionVi?: string;
  keyword: string; // Tên hiển thị (e.g. "Click")
  activityPackageId: string;
  keywordName: string; // Tên decorator (e.g. "Click")
  pythonMethod: string; // Tên hàm python (e.g. "click")
  isAutoGenerated: boolean;
  lineNumber?: number | null;
  type?: string; // e.g. "activity"
  iconCode?: string; // e.g. "FaMousePointer"
  arguments: ActivityArgument[];
  returnValue?: ActivityReturnValue | null;
}

export interface ParsedKeyword {
  name: string;
  methodName: string;
  args: { name: string; required: boolean; type?: string }[];
  docstring?: string;
  lineNumber?: number;
}

export interface ParsedClass {
  name: string;
  methods: string[];
  docstring?: string;
}

export interface SuggestedTemplate {
  displayName: string;
  description?: string;
  keywordName: string;
  pythonMethod: string;
  inputSchema: {
    label: string;
    type: string;
    required: boolean;
  }[];
}

export interface ActivityPackage {
  id: string; // e.g. "browser_automation"
  displayName: string; // e.g. "Browser automation"
  displayNameVi?: string;
  description?: string;
  descriptionVi?: string;
  imageKey?: string | null;
  library: string; // e.g. "RPA.Browser.Playwright"
  version: string;
  isActive: boolean;
  
  // Library file details
  libraryFileName?: string | null;
  libraryFileType?: string | null;
  libraryS3Bucket?: string | null;
  libraryS3Key?: string | null;
  libraryS3Url?: string | null;
  libraryChecksum?: string | null;
  libraryVersion?: string | null;
  
  // Parse results
  parsedKeywords?: ParsedKeyword[] | null;
  parsedClasses?: ParsedClass[] | null;
  imports?: string[] | null;
  parseStatus?: 'pending' | 'success' | 'failed' | 'not_applicable';
  parseError?: string | null;
  
  createdAt?: string;
  updatedAt?: string;
  
  activityTemplates?: ActivityTemplate[];
  
  // Backward compatibility alias (if needed)
  name?: string; 
}

export interface CreatePackageRequest {
  id?: string;
  name?: string;
  displayName: string;
  description?: string;
  library?: string;
  version?: string;
  libraryVersion?: string;
  file?: File;
}
